# Generated by Django 5.2.8 on 2025-11-29 11:42

import django.db.models.deletion
import illustrations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illustrations.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illustrations.enginemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IllustrationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=illustrations.models.illustration_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('illustration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='illustrations.illustration')),
            ],
        ),
        migrations.AddField(
            model_name='carmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illustrations.manufacturer'),
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illustrations.enginemodel')),
            ],
        ),
        migrations.AddField(
            model_name='illustration',
            name='part_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illustrations.partcategory'),
        ),
        migrations.CreateModel(
            name='PartSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('part_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illustrations.partcategory')),
            ],
        ),
        migrations.AddField(
            model_name='illustration',
            name='part_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='illustrations.partsubcategory'),
        ),
    ]
