# Generated by Django 5.2.8 on 2025-12-12 22:37

import django.db.models.deletion
import illustrations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Engine name (e.g., A09C, 6HK1)', max_length=255)),
                ('engine_code', models.CharField(blank=True, help_text='Official engine code', max_length=255)),
                ('displacement', models.DecimalField(blank=True, decimal_places=2, help_text='Engine displacement in liters (e.g., 8.9)', max_digits=5, null=True)),
                ('horsepower', models.IntegerField(blank=True, help_text='Horsepower (HP)', null=True)),
                ('torque', models.IntegerField(blank=True, help_text='Torque (Nm)', null=True)),
                ('fuel_type', models.CharField(choices=[('diesel', 'ディーゼル'), ('petrol', 'ガソリン'), ('hybrid', 'ハイブリッド'), ('electric', '電気（EV）'), ('lpg', 'LPG（液化プロパンガス）')], default='diesel', max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Engine Model',
                'verbose_name_plural': 'Engine Models',
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Car model name (e.g., Profia, Ranger)', max_length=255)),
                ('vehicle_type', models.CharField(blank=True, choices=[('truck_2t', '2tクラス'), ('truck_3t', '3tクラス'), ('truck_4t', '4tクラス'), ('truck_10t', '10tクラス'), ('truck_light_duty', '小型トラック'), ('truck_medium_duty', '中型トラック'), ('large_2_axle', '大型2軸'), ('large_3_axle', '大型3軸'), ('large_4_axle', '大型4軸'), ('kei_truck', '軽トラック'), ('kei_van', '軽バン'), ('kei_passenger', '軽自動車'), ('van_standard', 'バン'), ('cargo_van', 'カーゴバン'), ('hiace_class', 'ハイエースクラス'), ('caravan_class', 'キャラバンクラス'), ('sedan', 'セダン'), ('suv', 'SUV'), ('wagon', 'ワゴン'), ('hatchback', 'ハッチバック'), ('mpv', 'ミニバン/MPV'), ('bus_small', '小型バス'), ('bus_mid', '中型バス'), ('bus_large', '大型バス'), ('bus_7m_9m', 'バス 7m以上 9m未満'), ('wing_body', 'ウイング車'), ('flatbed', '平ボディ'), ('dump', 'ダンプ'), ('mixer', 'ミキサー車'), ('crane', 'クレーン付き'), ('reefer', '冷凍車'), ('tanker', 'タンクローリー'), ('trailer', 'トレーラー'), ('tractor_2_axle', 'トラクター2軸'), ('other', 'その他')], max_length=20)),
                ('year_from', models.IntegerField(blank=True, help_text='Production start year', null=True)),
                ('year_to', models.IntegerField(blank=True, help_text='Production end year (leave blank if still in production)', null=True)),
                ('model_code', models.CharField(blank=True, help_text='Model code (e.g., FR1EXEG)', max_length=100)),
                ('chassis_code', models.CharField(blank=True, help_text='Chassis code', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('engines', models.ManyToManyField(blank=True, help_text='Available engine options for this car model', related_name='car_models', to='illustrations.enginemodel')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='illustrations.manufacturer')),
            ],
            options={
                'verbose_name': 'Car Model',
                'verbose_name_plural': 'Car Models',
                'ordering': ['manufacturer', 'name'],
                'unique_together': {('manufacturer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_car_models', models.ManyToManyField(blank=True, help_text='Car models where this part is applicable', related_name='illustrations', to='illustrations.carmodel')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='illustrations.enginemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Illustration',
                'verbose_name_plural': 'Illustrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IllustrationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=illustrations.models.illustration_file_path)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('other', 'Other')], default='image', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('illustration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='illustrations.illustration')),
            ],
            options={
                'verbose_name': 'Illustration File',
                'verbose_name_plural': 'Illustration Files',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='enginemodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='illustrations.manufacturer'),
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Engine, Cooling System)', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_categories', to='illustrations.enginemodel')),
            ],
            options={
                'verbose_name': 'Part Category',
                'verbose_name_plural': 'Part Categories',
                'ordering': ['engine_model', 'name'],
                'unique_together': {('engine_model', 'name')},
            },
        ),
        migrations.AddField(
            model_name='illustration',
            name='part_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='illustrations.partcategory'),
        ),
        migrations.CreateModel(
            name='PartSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subcategory name (e.g., Pistons, Turbo)', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('part_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='illustrations.partcategory')),
            ],
            options={
                'verbose_name': 'Part Subcategory',
                'verbose_name_plural': 'Part Subcategories',
                'ordering': ['part_category', 'name'],
                'unique_together': {('part_category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='illustration',
            name='part_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='illustrations', to='illustrations.partsubcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='enginemodel',
            unique_together={('manufacturer', 'name')},
        ),
        migrations.AddIndex(
            model_name='illustration',
            index=models.Index(fields=['engine_model', 'part_category'], name='illustratio_engine__dab611_idx'),
        ),
        migrations.AddIndex(
            model_name='illustration',
            index=models.Index(fields=['user', 'created_at'], name='illustratio_user_id_a6db63_idx'),
        ),
    ]
