# Generated by Django 5.2.8 on 2025-12-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Part Category', 'verbose_name_plural': 'Part Categories'},
        ),
        migrations.AlterModelOptions(
            name='partsubcategory',
            options={'ordering': ['part_category', 'order', 'name'], 'verbose_name': 'Part Subcategory', 'verbose_name_plural': 'Part Subcategories'},
        ),
        migrations.AlterUniqueTogether(
            name='partcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='partcategory',
            name='name_ja',
            field=models.CharField(blank=True, help_text='Japanese name (e.g., エンジン本体)', max_length=255),
        ),
        migrations.AddField(
            model_name='partcategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower = first)'),
        ),
        migrations.AddField(
            model_name='partsubcategory',
            name='name_ja',
            field=models.CharField(blank=True, help_text='Japanese name (e.g., ピストン)', max_length=255),
        ),
        migrations.AddField(
            model_name='partsubcategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower = first)'),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='engine_model',
            field=models.ForeignKey(help_text='Which engine this illustration is for', on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='illustrations.enginemodel'),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='part_category',
            field=models.ForeignKey(help_text='Universal part category (e.g., Engine Components)', on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='illustrations.partcategory'),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='part_subcategory',
            field=models.ForeignKey(blank=True, help_text='Specific part type (e.g., Pistons)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='illustrations', to='illustrations.partsubcategory'),
        ),
        migrations.AlterField(
            model_name='partcategory',
            name='name',
            field=models.CharField(help_text='Category name (e.g., Engine Components)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='partcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='partsubcategory',
            name='name',
            field=models.CharField(help_text='Subcategory name (e.g., Pistons)', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='illustration',
            unique_together={('engine_model', 'part_category', 'part_subcategory', 'title')},
        ),
        migrations.RemoveField(
            model_name='partcategory',
            name='engine_model',
        ),
    ]
