# Generated by Django 5.2.8 on 2025-12-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0002_illustration_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='first_registration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='model_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enginemodel',
            name='engine_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
