# Generated by Django 5.2.8 on 2025-12-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0002_alter_partcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='country',
        ),
    ]
