# Generated by Django 5.2.8 on 2025-12-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0003_remove_manufacturer_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partcategory',
            name='name_ja',
        ),
        migrations.RemoveField(
            model_name='partsubcategory',
            name='name_ja',
        ),
        migrations.AlterField(
            model_name='enginemodel',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'ディーゼル'), ('petrol', 'ガソリン'), ('hybrid', 'ハイブリッド'), ('electric', '電気(EV)'), ('lpg', 'LPG(液化プロパンガス）')], default='diesel', max_length=20),
        ),
    ]
