# Generated by Django 5.2.8 on 2025-12-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0003_carmodel_chassis_number_carmodel_first_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
