# Generated by Django 5.2.8 on 2025-12-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0004_carmodel_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginemodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
