# Generated by Django 5.2.8 on 2025-12-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0004_remove_partcategory_name_ja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enginemodel',
            name='displacement',
        ),
        migrations.RemoveField(
            model_name='enginemodel',
            name='horsepower',
        ),
        migrations.RemoveField(
            model_name='enginemodel',
            name='torque',
        ),
    ]
