# Generated by Django 5.2.8 on 2025-12-11 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0005_alter_enginemodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enginemodel',
            options={'ordering': ['name'], 'verbose_name': 'Engine Model', 'verbose_name_plural': 'Engine Models'},
        ),
        migrations.AlterField(
            model_name='enginemodel',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='illustrations.carmodel'),
        ),
    ]
