# Generated by Django 5.2.8 on 2025-12-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0006_alter_enginemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='car_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
