# Generated by Django 5.2.8 on 2025-12-12 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0009_alter_carmodel_car_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='car_type',
            new_name='vehicle_type',
        ),
    ]
