# Generated by Django 5.2.8 on 2025-12-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0010_rename_car_type_carmodel_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('diesel', 'ディーゼル'), ('petrol', 'ガソリン'), ('hybrid', 'ハイブリッド'), ('electric', '電気（EV）'), ('lpg', 'LPG（液化プロパンガス）')], default='diesel', max_length=20),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('truck_2t', '2tクラス'), ('truck_3t', '3tクラス'), ('truck_4t', '4tクラス'), ('truck_10t', '10tクラス'), ('truck_light_duty', '小型トラック'), ('truck_medium_duty', '中型トラック'), ('large_2_axle', '大型2軸'), ('large_3_axle', '大型3軸'), ('large_4_axle', '大型4軸'), ('kei_truck', '軽トラック'), ('kei_van', '軽バン'), ('kei_passenger', '軽自動車'), ('van_standard', 'バン'), ('cargo_van', 'カーゴバン'), ('hiace_class', 'ハイエースクラス'), ('caravan_class', 'キャラバンクラス'), ('sedan', 'セダン'), ('suv', 'SUV'), ('wagon', 'ワゴン'), ('hatchback', 'ハッチバック'), ('mpv', 'ミニバン/MPV'), ('bus_small', '小型バス'), ('bus_mid', '中型バス'), ('bus_large', '大型バス'), ('bus_7m_9m', 'バス 7m以上 9m未満'), ('wing_body', 'ウイング車'), ('flatbed', '平ボディ'), ('dump', 'ダンプ'), ('mixer', 'ミキサー車'), ('crane', 'クレーン付き'), ('reefer', '冷凍車'), ('tanker', 'タンクローリー'), ('trailer', 'トレーラー'), ('tractor_2_axle', 'トラクター2軸'), ('other', 'その他')], default='truck', max_length=20),
        ),
    ]
