# Generated by Django 5.2.8 on 2025-12-27 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_factory_user_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='factory',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.factory'),
        ),
    ]
