# Generated by Django 5.2.8 on 2025-12-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
