# Generated by Django 5.2.8 on 2025-12-28 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='factory',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.factory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
