# Generated by Django 5.2.8 on 2026-01-05 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_factory_alter_user_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor'), ('WORKER', 'Worker'), ('VIEWER', 'Viewer')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_jobs', models.BooleanField(default=False)),
                ('can_view_finance', models.BooleanField(default=False)),
                ('can_edit_finance', models.BooleanField(default=False)),
                ('can_create_illustrations', models.BooleanField(default=False)),
                ('can_edit_illustrations', models.BooleanField(default=False)),
                ('can_delete_illustrations', models.BooleanField(default=False)),
                ('can_view_all_factory_illustrations', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='factory',
        ),
        migrations.CreateModel(
            name='FactoryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.factory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Factory Member',
                'verbose_name_plural': 'Factory Members',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['user', 'factory', 'is_active'], name='accounts_fa_user_id_d43253_idx'), models.Index(fields=['factory', 'is_active'], name='accounts_fa_factory_4ac62e_idx')],
                'unique_together': {('user', 'factory')},
            },
        ),
    ]
