# Generated by Django 5.2.8 on 2026-01-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
