# Generated by Django 5.2.8 on 2026-01-19 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_role_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(help_text='Department name', max_length=100, verbose_name='部所名')),
                ('comment', models.TextField(help_text='Feedback comment', verbose_name='コメント')),
                ('star', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Star rating (1-5)', verbose_name='評価')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日付')),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted the comment (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='accounts_co_date_a4c7e8_idx'), models.Index(fields=['department_name'], name='accounts_co_departm_ababb0_idx')],
            },
        ),
    ]
