# Generated by Django 5.2.8 on 2026-01-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='can_create_illustrations',
            new_name='can_create_illustration',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='can_delete_illustrations',
            new_name='can_delete_illustration',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='can_edit_illustrations',
            new_name='can_edit_illustration',
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_all_systems',
            field=models.BooleanField(default=False, help_text='Full system access - can manage all factories and all data'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_factory',
            field=models.BooleanField(default=False, help_text='Can manage factory operations and settings'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_illustration',
            field=models.BooleanField(default=False),
        ),
    ]
