# Generated by Django 5.2.8 on 2026-01-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_increase_role_code_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_catalog',
            field=models.BooleanField(default=False, help_text='Can manage manufacturers, car models, engine models, and categories'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_feedback',
            field=models.BooleanField(default=False, help_text='Can view and manage user feedback and comments'),
        ),
    ]
