# Generated by Django 5.2.8 on 2026-01-27 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_role_can_manage_catalog_role_can_manage_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Backup username in case user is deleted', max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('VIEW', 'Viewed'), ('LOGIN', 'Logged In'), ('LOGOUT', 'Logged Out'), ('DOWNLOAD', 'Downloaded'), ('UPLOAD', 'Uploaded'), ('EXPORT', 'Exported'), ('IMPORT', 'Imported')], db_index=True, help_text='Type of action performed', max_length=20)),
                ('model_name', models.CharField(db_index=True, help_text='Name of the model affected (e.g., Illustration, User)', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='ID of the object affected', max_length=100, null=True)),
                ('object_repr', models.CharField(help_text='Human-readable representation of the object', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('changes', models.JSONField(blank=True, help_text='Before/after values for updates', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('endpoint', models.CharField(help_text='API endpoint called', max_length=500)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, PUT, DELETE)', max_length=10)),
                ('success', models.BooleanField(default=True, help_text='Whether the action completed successfully')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('factory', models.ForeignKey(blank=True, help_text='Factory context if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='accounts.factory')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'user'], name='accounts_ac_timesta_df1272_idx'), models.Index(fields=['model_name', '-timestamp'], name='accounts_ac_model_n_d70c39_idx'), models.Index(fields=['action', '-timestamp'], name='accounts_ac_action_448a74_idx')],
            },
        ),
    ]
