# Generated by Django 5.2.8 on 2026-01-05 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_bio'),
        ('illustrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='illustration',
            name='factory',
            field=models.ForeignKey(blank=True, editable=False, help_text='The factory this illustration belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='illustrations', to='accounts.factory'),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='user',
            field=models.ForeignKey(editable=False, help_text='Automatically set to the creating user', on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='illustration',
            index=models.Index(fields=['factory'], name='illustratio_factory_031957_idx'),
        ),
    ]
