# Generated by Django 5.2.8 on 2025-12-27 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_factory_user_factory'),
        ('illustrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustration',
            name='factory',
            field=models.ForeignKey(blank=True, help_text='Factory that owns this illustration', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='illustrations', to='accounts.factory'),
        ),
    ]
