# Generated by Django 5.2.8 on 2026-01-14 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_role_code'),
        ('illustrations', '0002_illustration_factory_alter_illustration_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustration',
            name='factory',
            field=models.ForeignKey(blank=True, editable=False, help_text='The factory this illustration belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='illustrations', to='accounts.factory'),
        ),
    ]
