# Generated by Django 5.2.8 on 2025-12-27 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_factory'),
        ('illustrations', '0002_illustration_factory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustration',
            name='factory',
            field=models.ForeignKey(blank=True, editable=False, help_text="Automatically set from user's factory", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='illustrations', to='accounts.factory'),
        ),
        migrations.AddIndex(
            model_name='illustration',
            index=models.Index(fields=['factory'], name='illustratio_factory_031957_idx'),
        ),
    ]
