# Generated by Django 5.2.8 on 2026-01-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0003_alter_illustration_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustrationfile',
            name='title',
            field=models.CharField(blank=True, help_text='User-friendly title for the file', max_length=255),
        ),
    ]
