# Generated by Django 5.2.8 on 2025-12-27 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0003_alter_illustration_factory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustration',
            name='user',
            field=models.ForeignKey(editable=False, help_text='Automatically set to the creating user', on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
