# Generated by Django 5.2.8 on 2026-01-18 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0004_illustrationfile_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteIllustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('illustration', models.ForeignKey(help_text='The favorited illustration', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='illustrations.illustration')),
                ('user', models.ForeignKey(help_text='User who favorited this illustration', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_illustrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Illustration',
                'verbose_name_plural': 'Favorite Illustrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='illustratio_user_id_a216db_idx')],
                'unique_together': {('user', 'illustration')},
            },
        ),
    ]
