# Generated by Django 5.2.8 on 2026-01-18 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0005_favoriteillustration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteillustration',
            options={'ordering': ['-created_at'], 'verbose_name': 'お気に入り', 'verbose_name_plural': 'お気に入り'},
        ),
    ]
