# Generated by Django 5.2.8 on 2026-01-23 10:25

import apps.illustrations.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0006_alter_favoriteillustration_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedIllustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_file', models.FileField(help_text='The edited PDF file', upload_to=apps.illustrations.models.submitted_illustration_path)),
                ('recipient_email', models.EmailField(blank=True, help_text='Email recipient', max_length=254)),
                ('subject', models.CharField(blank=True, help_text='Email subject', max_length=500)),
                ('body', models.TextField(blank=True, help_text='Email body')),
                ('status', models.CharField(choices=[('saved', '保存済み'), ('email_sent', 'メール送信済み')], default='saved', help_text='Submission status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_file', models.ForeignKey(blank=True, help_text='Original file that was edited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='illustrations.illustrationfile')),
                ('original_illustration', models.ForeignKey(blank=True, help_text='Original illustration this was based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='illustrations.illustration')),
                ('user', models.ForeignKey(help_text='User who submitted this edited PDF', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_illustrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submitted Illustration',
                'verbose_name_plural': 'Submitted Illustrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='illustratio_user_id_d39575_idx'), models.Index(fields=['status'], name='illustratio_status_fd5188_idx')],
            },
        ),
    ]
