# Generated by Django 5.2.8 on 2026-01-24 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0007_submittedillustration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmittedIllustration',
        ),
    ]
